export const NAME_EPICS = {
  EPIC_CHECK_LIST_TASK_SCREEN: {
    EPIC_CHECK_LIST_TASK_SCREEN: 'EPIC_CHECK_LIST_TASK_SCREEN',
    EPIC_GET_LIST_CHECK_LIST: 'EPIC_GET_LIST_CHECK_LIST',
    EPIC_GET_LIST_CHECK_LIST_FAIL: 'EPIC_GET_LIST_CHECK_LIST_FAIL',
    EPIC_CREATE_CHECK_LIST : 'EPIC_CREATE_CHECK_LIST',
    EPIC_CREATE_CHECK_LIST_FAIL : 'EPIC_CREATE_CHECK_LIST_FAIL',
    EPIC_GET_LIST_CHECK_LIST_TYPE : 'EPIC_GET_LIST_CHECK_LIST_TYPE',
    EPIC_GET_LIST_CHECK_LIST_TYPE_FAIL : 'EPIC_GET_LIST_CHECK_LIST_TYPE_FAIL',
    EPIC_CREATE_CHECK_LIST_ITEM: 'EPIC_CREATE_CHECK_LIST_ITEM',
    EPIC_CREATE_CHECK_LIST_ITEM_FAIL: 'EPIC_CREATE_CHECK_LIST_ITEM_FAIL',
    EPIC_DELETE_CHECK_LIST_ITEM:'EPIC_DELETE_CHECK_LIST_ITEM',
    EPIC_DELETE_CHECK_LIST_ITEM_FAIL: 'EPIC_DELETE_CHECK_LIST_ITEM_FAIL',
    EPIC_CREATE_CHECK_LIST_TITLE: 'EPIC_CREATE_CHECK_LIST_TITLE',
    EPIC_CREATE_CHECK_LIST_TITLE_FAIL: 'EPIC_CREATE_CHECK_LIST_TITLE_FAIL'
  },
};
