export const NAME_ACTIONS = {
  TASK_SCREEN: {
    TASK_SCREEN:'TASK_SCREEN',
    GET_LIST_TASK: 'GET_LIST_TASK',
    GET_LIST_TASK_FAILED:'GET_LIST_TASK_FAILED',
    GET_DETAIL_TASK:'GET_DETAIL_TASK',
    GET_DETAIL_TASK_FAILED:'GET_DETAIL_TASK_FAILED',
    CREATE_TASK:'CREATE_TASK',
    CREATE_TASK_FAILED:'CREATE_TASK_FAILED',
    GET_LIST_TASK_OF_PROJECT:'GET_LIST_TASK_OF_PROJECT',
    GET_LIST_TASK_OF_PROJECT_FAILED:'GET_LIST_TASK_OF_PROJECT_FAILED',
    EDIT_TASK:'EDIT_TASK',
    EDIT_TASK_FAILED:'EDIT_TASK_FAILED',
    RESET_DETAIL_TASK : 'RESET_DETAIL_TASK',
    RESET_DETAIL_TASK_FAIL : 'RESET_DETAIL_TASK_FAIL'

  },
};
