export const NAME_EPICS = {
    EPIC_PROJECT_SCREEN: {
        EPIC_PROJECT_SCREEN:'EPIC_PROJECT_SCREEN',
        EPIC_GET_PROJECT_COMPANY:'EPIC_GET_PROJECT_COMPANY',
        EPIC_GET_PROJECT_COMPANY_FAILED:'EPIC_GET_PROJECT_COMPANY_FAILED',

        EPIC_GET_PROJECT_STATUS:'EPIC_GET_PROJECT_STATUS',
        EPIC_GET_PROJECT_STATUS_FAILED:'EPIC_GET_PROJECT_STATUS_FAILED',

        EPIC_GET_DETAIL_PROJECT:'EPIC_GET_DETAIL_PROJECT',
        EPIC_GET_DETAIL_PROJECT_FAILED:'EPIC_GET_DETAIL_PROJECT_FAILED',
        
        EPIC_EDIT_PROJECT:'EPIC_EDIT_PROJECT',
        EPIC_EDIT_PROJECT_FAILED:'EPIC_EDIT_PROJECT_FAILED',
        EPIC_SELECT_PROJECT:'EPIC_SELECT_PROJECT',
        EPIC_SELECT_PROJECT_FAILED:'EPIC_SELECT_PROJECT_FAILED',

        EPIC_SEARCH_LIST_PROJECT:'EPIC_SEARCH_LIST_PROJECT',
        EPIC_SEARCH_LIST_PROJECT_FAILED:'EPIC_SEARCH_LIST_PROJECT_FAILED'
    
    },
}