export const NAME_ACTIONS = {
    USER_SCREEN: {
        USER_SCREEN: 'USER_SCREEN',
        GET_LIST_USER_COMPANY: 'GET_LIST_USER_COMPANY',
        GET_LIST_USER_COMPANY_FAILED: 'GET_LIST_USER_COMPANY_FAILED',
        GET_LIST_USER_BY_ID: 'GET_LIST_USER_BY_ID',
        GET_LIST_USER_BY_ID_FAILED: 'GET_LIST_USER_BY_ID_FAILED',
        //test
        SELECT_USER_PROJECT:'SELECT_USER_PROJECT',
        SELECT_USER_PROJECT_FAILED:'SELECT_USER_PROJECT_FAILED',

        REMOVED_SELECT_USER_PROJECT:'REMOVED_SELECT_USER_PROJECT',
        REMOVED_SELECT_USER_PROJECT_FAILED:'REMOVED_SELECT_USER_PROJECT_FAILED',

        CLEAR_SELECT_USER_PROJECT:'CLEAR_SELECT_USER_PROJECT',
        CLEAR_SELECT_USER_PROJECT_FAILED:'CLEAR_SELECT_USER_PROJECT_FAILED',

        GET_LIST_USER_PROJECT_ID: 'GET_LIST_USER_PROJECT_ID',
        GET_LIST_USER_PROJECT_ID_FAILED: 'GET_LIST_USER_PROJECT_ID_FAILED'
    },
};