export const NAME_EPICS = {
    EPIC_TASK_TYPE_SCREEN: {
        EPIC_TASK_TYPE_SCREEN:'EPIC_TASK_TYPE_SCREEN',
        EPIC_GET_LIST_TASK_TYPE:'EPIC_GET_LIST_TASK_TYPE',
        EPIC_GET_LIST_TASK_TYPE_FAILED:'EPIC_GET_LIST_TASK_TYPE_FAILED',
        EPIC_SEARCH_LIST_TASK_:'EPIC_SEARCH_LIST_TASK_',
        EPIC_SEARCH_LIST_TASK_FAILED:'EPIC_SEARCH_LIST_TASK_FAILED',
        EPIC_GET_LIST_TASK_TYPE_2:'EPIC_GET_LIST_TASK_TYPE_2',
        EPIC_GET_LIST_TASK_TYPE_2_FAILED:'EPIC_GET_LIST_TASK_TYPE_2_FAILED'
    },
  };