export const NAME_ACTIONS = {
    PROJECT_TYPE_SCREEN: {
        PROJECT_TYPE_SCREEN: 'PROJECT_TYPE_SCREEN',
        GET_ALL_PROJECT_TYPE:'GET_ALL_PROJECT_TYPE',
        GET_ALL_PROJECT_TYPE_FAILED:'GET_ALL_PROJECT_TYPE_FAILED',
        GET_ALL_TASK_TYPE:'GET_ALL_TASK_TYPE',
        GET_ALL_TASK_TYPE_FAILED:'GET_ALL_TASK_TYPE_FAILED'
    }
  };