export const NAME_EPICS = {
    EPIC_ATTACHMENT: {
        EPIC_ATTACHMENT: 'EPIC_ATTACHMENT',
        EPIC_CREATE_ATTACHMENT: 'EPIC_CREATE_ATTACHMENT',
        EPIC_CREATE_ATTACHMENT_FAILED: 'EPIC_CREATE_ATTACHMENT_FAILED'
    },
}