export const NAME_ACTIONS = {
  CHECK_lIST_TASK_SCREEN: {
      CHECK_LIST_TASK: 'CHECK_LIST_TASK',
      GET_CHECK_LIST:'GET_CHECK_LIST',
      GET_CHECK_LIST_FAIL:'GET_CHECK_LIST_FAIL',
      CREATE_CHECK_LIST:'CREATE_CHECK_LIST',
      CREATE_CHECK_LIST_FAIL:'CREATE_CHECK_LIST_FAIL',
      GET_LIST_CHECK_LIST_TYPE:'GET_LIST_CHECK_LIST_TYPE',
      GET_LIST_CHECK_LIST_TYPE_FAIL:'GET_LIST_CHECK_LIST_TYPE_FAIL',
      CRATE_CHECK_LIST_ITEM: 'CREATE_CHECK_LIST_ITEM',
      CRATE_CHECK_LIST_ITEM_FAIL: 'CREATE_CHECK_LIST_ITEM_FAIL',
      DELETE_CHECK_LIST_ITEM_FAIL: 'DELETE_CHECK_LIST_ITEM_FAIL',
      DELETE_CHECK_LIST_ITEM: 'DELETE_CHECK_LIST_ITEM',
  },
};