export const NAME_EPICS = {
    EPIC_TASK_SCREEN: {
        EPIC_TASK_SCREEN: 'EPIC_TASK_SCREEN',
        EPIC_GET_LIST_TASK: 'EPIC_GET_LIST_TASK',
        EPIC_GET_LIST_TASK_FAILED: 'EPIC_GET_LIST_TASK_FAILED',
        EPIC_GET_DETAIL_TASK:'EPIC_GET_DETAIL_TASK',
        EPIC_GET_DETAIL_TASK_FAILED:'EPIC_GET_DETAIL_TASK_FAILED',
        EPIC_CREATE_TASK:'EPIC_CREATE_TASK',
        EPIC_CREATE_TASK_FAILED:'EPIC_CREATE_TASK_FAILED',
        EPIC_GET_LIST_TASK_OF_PROJECT:'EPIC_GET_LIST_TASK_OF_PROJECT',
        EPIC_GET_LIST_TASK_OF_PROJECT_FAILED:'EPIC_GET_LIST_TASK_OF_PROJECT_FAILED',
        EPIC_EDIT_TASK:'EPIC_EDIT_TASK',
        EPIC_EDIT_TASK_FAILED:'EPIC_EDIT_TASK_FAILED',
        EPIC_RESET_DETAIL_TASK : 'EPIC_RESET_DETAIL_TASK',
    }
}