export const NAME_EPICS = {
    EPIC_PROJECT_TYPE_SCREEN: {
        EPIC_PROJECT_TYPE_SCREEN: 'EPIC_PROJECT_TYPE_SCREEN',
        EPIC_GET_ALL_PROJECT_TYPE:'EPIC_GET_ALL_PROJECT_TYPE',
        EPIC_GET_ALL_PROJECT_TYPE_FAILED:'EPIC_GET_ALL_PROJECT_TYPE_FAILED',
        EPIC_GET_ALL_TASK_TYPE:'EPIC_GET_ALL_TASK_TYPE',
        EPIC_GET_ALL_TASK_TYPE_FAILED:'EPIC_GET_ALL_TASK_TYPE_FAILED'
        
    }
  };