export const NAME_ACTIONS = {
  PROJECT_SCREEN: {
    PROJECT_SCREEN: 'PROJECT_SCREEN',
    GET_PROJECT_COMPANY: 'GET_PROJECT_COMPANY',
    GET_PROJECT_COMPANY_FAILED: 'GET_PROJECT_COMPANY_FAILED',

    GET_PROJECT_STATUS: 'GET_PROJECT_STATUS',
    GET_PROJECT_STATUS_FAILED: 'GET_PROJECT_STATUS_FAILED',


    GET_DETAIL_PROJECT:'GET_DETAIL_PROJECT',
    GET_DETAIL_PROJECT_FAILED:'GET_DETAIL_PROJECT_FAILED',
    EDIT_PROJECT:'EDIT_PROJECT',
    EDIT_PROJECT_FAILED:'EDIT_PROJECT_FAILED',
    SELECT_PROJECT:'SELECT_PROJECT',
    SELECT_PROJECT_FAILED:'SELECT_PROJECT_FAILED',

    SEARCH_LIST_PROJECT:'SEARCH_LIST_PROJECT',
    SEARCH_LIST_PROJECT_FAILED:'SEARCH_LIST_PROJECT_FAILED',
    
  }
};
