export const NAME_ACTIONS = {
    ATTACHMENT: {
        ATTACHMENT: 'ATTACHMENT',
        CREATE_ATTACHMENT: 'CREATE_ATTACHMENT',
        CREATE_ATTACHMENT_FAILED: 'CREATE_ATTACHMENT_FAILED'
    },
};
