export const NAME_ACTIONS = {
    TASK_TYPE_SCREEN: {
        TASK_TYPE_SCREEN:'TASK_TYPE_SCREEN',
        GET_LIST_TASK_TYPE:'GET_LIST_TASK_TYPE',
        GET_LIST_TASK_TYPE_FAILED:'GET_LIST_TASK_TYPE_FAILED',
        SEARCH_LIST_TASK:'SEARCH_LIST_TASK',
        SEARCH_LIST_TASK_FAILED:'SEARCH_LIST_TASK_FAILED',
        GET_LIST_TASK_TYPE_2:'GET_LIST_TASK_TYPE_2',
        GET_LIST_TASK_TYPE_2_FAILED:'GET_LIST_TASK_TYPE_2_FAILED'
    },
  };
  