export const NAME_EPICS = {
    EPIC_USER_SCREEN: {
        EPIC_USER_SCREEN: 'EPIC_USER_SCREEN',
        EPIC_GET_LIST_USER_COMPANY: 'EPIC_GET_LIST_USER_COMPANY',
        EPIC_GET_LIST_USER_COMPANY_FAILED: 'EPIC_GET_LIST_USER_COMPANY_FAILED',
        EPIC_GET_LIST_USER_BY_ID: 'EPIC_GET_LIST_USER_BY_ID',
        EPIC_GET_LIST_USER_BY_ID_FAILED: 'EPIC_GET_LIST_USER_BY_ID_FAILED',
        EPIC_SELECT_USER_PROJECT:'EPIC_SELECT_USER_PROJECT',
        EPIC_SELECT_USER_PROJECT_FAILED:'EPIC_SELECT_USER_PROJECT_FAILED',
        EPIC_REMOVED_SELECT_USER_PROJECT:'EPIC_REMOVED_SELECT_USER_PROJECT',
        EPIC_REMOVED_SELECT_USER_PROJECT_FAILED:'EPIC_REMOVED_SELECT_USER_PROJECT_FAILED',
        EPIC_CLEAR_SELECT_USER_PROJECT:'EPIC_CLEAR_SELECT_USER_PROJECT',
        EPIC_CLEAR_SELECT_USER_PROJECT_FAILED:'EPIC_CLEAR_SELECT_USER_PROJECT_FAILED',
  
        EPIC_GET_LIST_USER_PROJECT_ID: 'EPIC_GET_LIST_USER_PROJECT_ID',
        EPIC_GET_LIST_USER_PROJECT_ID_FAILED: 'EPIC_GET_LIST_USER_PROJECT_ID_FAILED'
    },
}