export const NAME_ACTIONS = {
    PARTNER_SCREEN: {
        PARTNER_SCREEN: 'PARTNER_SCREEN',
        GET_LIST_PARTNER:'GET_LIST_PARTNER',
        GET_LIST_PARTNER_FAILED:'GET_LIST_PARTNER_FAILED',
        SEARCH_PARTNER:'SEARCH_PARTNER',
        SEARCH_PARTNER_FAILED: 'SEARCH_PARTNER_FAILED'
    },
};