export const NAME_EPICS = {
    EPIC_PARTNER_SCREEN: {
        EPIC_PARTNER_SCREEN: 'EPIC_PARTNER_SCREEN',
        EPIC_GET_LIST_PARTNER:'EPIC_GET_LIST_PARTNER',
        EPIC_GET_LIST_PARTNER_FAILED:'EPIC_GET_LIST_PARTNER_FAILED',
        EPIC_SEARCH_PARTNER:'EPIC_SEARCH_PARTNER',
        EPIC_SEARCH_PARTNER_FAILED: 'EPIC_SEARCH_PARTNER_FAILED'
    },
}