export const NAME_EPICS = {
    EPIC_LOGIN_SCREEN: {
        EPIC_LOGIN_SCREEN: 'EPIC_LOGIN_SCREEN',
        EPIC_LOGIN_ERP: 'EPIC_LOGIN_ERP',
        EPIC_LOGIN_ERP_FAILED: 'EPIC_LOGIN_ERP_FAILED',
        EPIC_LOGOUT: 'EPIC_LOGOUT',
        EPIC_LOGOUT_FAILED: 'EPIC_LOGOUT_FAILED'
    }
}