export const NAME_ACTIONS = {
    LOGIN_SCREEN: {
        LOGIN_SCREEN: 'LOGIN_SCREEN',
        LOGIN_ERP: 'LOGIN_ERP',
        LOGIN_ERP_FAILED: 'LOGIN_ERP_FAILED',
        LOGOUT: 'LOGOUT',
        LOGOUT_FAILED:'LOGOUT_FAILED'
    }
}